import { AxiosResponse } from 'axios'
import { GetServerSideProps } from 'next'
import Head from 'next/head'
import React from 'react'
import Tabs from '../../components/Tabs'
import { fetchCategories } from '../../http'
import { ICategory, ICollectionResponse, IPagination } from '../../types'
import { capitalizeFirstLetter } from '../../utils'

interface IPropType {
  categories: {
    items: ICategory[],
    pagination: IPagination
  }
}
function category({ categories }: IPropType) {
  const formatedCategory = () => {
    return capitalizeFirstLetter('TEST APP')
  }
  return (
    <>
      <Head>
        <title>Blog Next {formatedCategory()}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tabs categories={categories.items}/>
    </>
  )
}

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  const {
    data: categories,
  }: AxiosResponse<ICollectionResponse<ICategory[]>> =
    await fetchCategories();
  return {
    props: {
      categories: {
        items: categories.data,
        pagination: categories.meta.pagination
      },
    }
  }
}

export default category